"""Type stubs for cspyce (SPICE toolkit)."""

from __future__ import annotations

from typing import Any

def furnsh(path: str) -> None: ...
def spkapp(
    targ: int,
    et: float,
    ref: str,
    sobs: list[float] | Any,
    abcorr: str,
) -> tuple[tuple[float, float, float, float, float, float], float]: ...
def spkssb(body: int, et: float, ref: str) -> tuple[float, float, float, float, float, float]: ...
def bodvar(bodyid: int, item: str) -> tuple[float, ...]: ...
def bodfnd(bodyid: int, item: str) -> bool: ...
def bodvrd(body: str, item: str) -> tuple[float, ...]: ...
def bodc2n(bodyid: int) -> str: ...
def bodn2c(name: str) -> int: ...
def tipbod(ref: str, body: int, et: float) -> tuple[tuple[float, float, float], ...]: ...
def spkez(
    targ: int,
    et: float,
    ref: str,
    abcorr: str,
    obs: int,
) -> tuple[tuple[float, float, float, float, float, float], float]: ...
def twovec(
    vec1: tuple[float, float, float] | Any,
    ax1: int,
    vec2: tuple[float, float, float] | Any,
    ax2: int,
) -> tuple[tuple[float, float, float], ...]: ...
def recrad(rectan: tuple[float, float, float] | Any) -> tuple[float, float, float]: ...
def radrec(
    r: float, colat: float, lon: float
) -> tuple[float, float, float]: ...
def vperp(
    v1: tuple[float, float, float] | Any,
    v2: tuple[float, float, float] | Any,
) -> tuple[float, float, float]: ...
def vminus(v: tuple[float, float, float] | Any) -> tuple[float, float, float]: ...
def vsep(v1: tuple[float, float, float] | Any, v2: tuple[float, float, float] | Any) -> float: ...
def vnorm(v: tuple[float, float, float] | Any) -> float: ...
def clight() -> float: ...
def mxv(
    mat: tuple[tuple[float, float, float], ...] | Any,
    vin: tuple[float, float, float] | Any,
) -> tuple[float, float, float]: ...
def ucrss(
    v1: tuple[float, float, float] | Any,
    v2: tuple[float, float, float] | Any,
) -> tuple[float, float, float]: ...
def vcrss(
    v1: tuple[float, float, float] | Any,
    v2: tuple[float, float, float] | Any,
) -> tuple[float, float, float]: ...
def vhat(v: tuple[float, float, float] | Any) -> tuple[float, float, float]: ...
def vlcom(
    a: float,
    v1: tuple[float, float, float] | Any,
    b: float,
    v2: tuple[float, float, float] | Any,
) -> tuple[float, float, float]: ...
def georec(
    lon: float,
    lat: float,
    alt: float,
    re: float,
    f: float,
) -> tuple[float, float, float]: ...
def pxform(fromref: str, toref: str, et: float) -> tuple[tuple[float, float, float], ...]: ...
def mtxv(
    mat: tuple[tuple[float, float, float], ...] | Any,
    vin: tuple[float, float, float] | Any,
) -> tuple[float, float, float]: ...
