"""Escher PostScript output layer — Python port of FORTRAN Escher library.

Abstract
--------
Draw segments generated by Euclid. Escher is the device handler for Euclid: it
accepts segments (two endpoints and a color) from Euclid, clips them, buffers
them internally to reduce I/O, and draws them on the target graphics device
(here, PostScript).

Particulars
-----------
Escher has several entry points: esview, esdraw, esdump, esclr (and esfile,
esopen, esdr07, eslwid, eswrit, esmove, escl07, espl07 for PostScript output).
Each is documented in its module. Escher is never called directly as a single
routine; call the entry points instead.

This package replicates the exact PostScript output from the FORTRAN esdv07.f,
esfile.f, eslwid.f, eswrit.f, esmove.f so that Python viewer output can match
FORTRAN byte-for-byte. Coordinate system: 0.1 0.1 scale (1 unit = 0.1 points);
all coordinates are integers in this scaled space.
"""

from ephemeris_tools.rendering.escher.constants import MAXX, MAXY, MINX, MINY
from ephemeris_tools.rendering.escher.ps_output import (
    escl07,
    esdr07,
    esfile,
    eslwid,
    esmove,
    esopen,
    espl07,
    eswrit,
    write_ps_header,
)
from ephemeris_tools.rendering.escher.state import EscherState, EscherViewState
from ephemeris_tools.rendering.escher.view import esclr, esdraw, esdump, esview

__all__: list[str] = [
    'MAXX',
    'MAXY',
    'MINX',
    'MINY',
    'EscherState',
    'EscherViewState',
    'escl07',
    'esclr',
    'esdr07',
    'esdraw',
    'esdump',
    'esfile',
    'eslwid',
    'esmove',
    'esopen',
    'espl07',
    'esview',
    'eswrit',
    'write_ps_header',
]
