"""Type stubs for rms-julian."""

from __future__ import annotations

def set_ut_model(model: str) -> None: ...
def load_lsk(path: str | None = None) -> None: ...
def day_sec_from_string(string: str) -> tuple[int, float]: ...
def tai_from_day_sec(day: int, sec: float) -> float: ...
def tdb_from_tai(tai: float) -> float: ...
def tai_from_tdb(tdb: float) -> float: ...
def mjd_from_tai(tai: float) -> float: ...
def day_sec_from_tai(tai: float) -> tuple[int, float]: ...
def ymd_from_day(day: int) -> tuple[int, int, int]: ...
def yd_from_day(day: int) -> tuple[int, int]: ...
def hms_from_sec(sec: float) -> tuple[int, int, float]: ...
def tai_from_jd(jd: float) -> float: ...
def day_from_ymd(year: int, month: int, day: int) -> int: ...
def format_tai(tai: float, fmt: str | None = None) -> str: ...
